version: '3'

services:
  mysqldb-customers:
    image: mysql:8.0
    container_name: mysqldb-customers
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customers
      - MYSQL_TCP_PORT=3306

  customers-svc:
    build:
      context: ./app/customers
    container_name: customers-svc
    restart: always
    mem_limit: 512M
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb-customers/customers
      - MYSQL_USER=root
      - MYSQL_PASS=root
    depends_on:
      - mysqldb-customers
    ports:
      - 8081:8081

  mysqldb-visits:
    image: mysql:8.0
    container_name: mysqldb-visits
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=visits
      - MYSQL_TCP_PORT=3306
  
  visits-svc:
    build:
      context: ./app/visits
    container_name: visits-svc
    restart: always
    mem_limit: 512M
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb-visits/visits
      - MYSQL_USER=root
      - MYSQL_PASS=root
    depends_on:
      - mysqldb-visits
    ports:
      - 8082:8082

  mysqldb-vets:
    image: mysql:8.0
    container_name: mysqldb-vets
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vets
      - MYSQL_TCP_PORT=3306

  vets-svc:
    build:
      context: ./app/vets
    container_name: vets-svc
    restart: always
    mem_limit: 512M
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb-vets/vets
      - MYSQL_USER=root
      - MYSQL_PASS=root
    depends_on:
      - mysqldb-vets
    ports:
      - 8083:8083
      
  kong:
    image: kong
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - vets-svc
      - visits-svc
      - customers-svc
    ports:
      - 8000:8000
      - 8001:8001

  configure-kong:
    build:
      context: ./app/kong
    container_name: configure-kong
    depends_on:
      - kong

  frontend:
    build:
      context: ./app/frontend
    container_name: frontend
    mem_limit: 512M
    environment:
      - APP_API=http://localhost:8000/
    depends_on:
      - vets-svc
      - visits-svc
      - customers-svc
      - kong
    ports:
      - 8080:8080