apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-customers
  name: app-customers
  namespace: aulainfra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-customers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: app-customers
    spec:
      containers:
      - image: aulainfraacr.azurecr.io/customers
        imagePullPolicy: Always
        name: backend-customers
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: TZ
          - name: MYSQL_URL
            valueFrom:
              configMapKeyRef:
                name: app-customers-configmap
                key: MYSQL_URL
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MYSQL_PASS
        ports:
          - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
