apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-visits
  name: app-visits
  namespace: aulainfra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-visits
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: app-visits
    spec:
      containers:
      - image: testemicroservicesacr.azurecr.io/visits
        imagePullPolicy: Always
        name: backend-visits
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: TZ
          - name: MYSQL_URL
            valueFrom:
              configMapKeyRef:
                name: app-visits-configmap
                key: MYSQL_URL
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: MYSQL_PASS
        ports:
          - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
