apiVersion: v1
kind: Service
metadata:
  name: mysqldb-vets
  namespace: aulainfra
spec:
  ports:
  - name: "tcp-3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysqldb-vets-stfs