apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
  namespace: aulainfra
spec:
  containers:
  - image: testemicroservicesacr.azurecr.io/configure-kong
    name: configure-kong
  restartPolicy: OnFailure