apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    name: myapp
  name: myapp
  namespace: aulainfra
spec:
  containers:
  - image: testemicroservicesacr.azurecr.io/configure-kong
    name: configure-kong
    resources: {}
  restartPolicy: OnFailure
status: {}