apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: springapi
  name: api-gateway
  namespace: aulainfra
spec:
  type: LoadBalancer
  ports:
  - name: "http-8000"
    port: 8000
    targetPort: 8000
  selector:
    app: api-gateway
    