apiVersion: v1
kind: Service
metadata:
  name: customers-svc
  namespace: aulainfra
spec:
  type: ClusterIP
  ports:
  - name: "http-8081"
    port: 8081
    targetPort: 8081
  selector:
    app: app-customers
    