apiVersion: v1
kind: Service
metadata:
  name: visits-svc
  namespace: aulainfra
spec:
  type: ClusterIP
  ports:
  - name: "http-8082"
    port: 8082
    targetPort: 8082
  selector:
    app: app-visits
    