apiVersion: v1
kind: Service
metadata:
  name: vets-svc
  namespace: aulainfra
spec:
  type: ClusterIP
  ports:
  - name: "http-8083"
    port: 8083
    targetPort: 8083
  selector:
    app: app-vets
    