apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: aulainfra
spec:
  type: ClusterIP
  ports:
  - name: "http-8001"
    port: 8001
    targetPort: 8001
  selector:
    app: api-gateway
    